### ISSUE TITLE
Interaction dataset process

### ISSUE THREAD

**Issue by WUT-wuxigang** [Xiaoyu006/MATP-with-HEAT#4]
I would like to ask a question about the dataset, what is the file level of the original Interaction dataset during data preprocessing. When running the data_pre_run.sh script, the generated heatmtp_it_data folder only contains the MAP.pt of each scene, and no data is generated in the val and train folders

**Comment by Jctrp** [comment]
Hi, I also met the same problem as you in the process of data processing I will keep an eye on this issue and share my mind if the point is found.

**Comment by Jctrp** [comment]
Hi, I also met the same problem as you in the process of data processing. I will keep an eye on this issue and share my mind if the point is found.

**Comment by Xiaoyu006** [comment]
Hi, @WUT-wuxigang and @Jctrp. Sorry for the inconvenience caused.

I uploaded a file showing the data structure and instructions to obtain the `sorted` folder. Hope this update helps.

I am going to close this issue. In case there are other problems with data processing, please reopen this issue or launch a new one. Thank you!

**Comment by WUT-wuxigang** [comment]
Thanks for your reply, I read your update carefully and I have generated a new question, how is validation-set-list_INTERACTION-dataset_v1.txt obtained during the track splitting process? Looking forward to your reply, thanks a lot!

从 Windows 版邮件发送

发件人: Xiaoyu006
发送时间: 2022年7月18日 14:30
主题: Re: [Xiaoyu006/MATP-with-HEAT] Interaction dataset process (Issue #4)

Hi, @WUT-wuxigang and @Jctrp. Sorry for the inconvenience caused.
I uploaded a file showing the data structure and instructions to obtain the sorted folder. Hope this update helps.
I am going to close this issue. In case there are other problems with data processing, please reopen this issue or launch a new one. Thank you!

**Comment by Xiaoyu006** [comment]
> Thanks for your reply, I read your update carefully and I have generated a new question, how is validation-set-list_INTERACTION-dataset_v1.txt obtained during the track splitting process? Looking forward to your reply, thanks a lot! 从 Windows 版邮件发送 发件人: Xiaoyu006 发送时间: 2022年7月18日 14:30 主题: Re: [Xiaoyu006/MATP-with-HEAT] Interaction dataset process (Issue #4) Hi, @WUT-wuxigang and @Jctrp. Sorry for the inconvenience caused. I uploaded a file showing the data structure and instructions to obtain the sorted folder. Hope this update helps. I am going to close this issue. In case there are other problems with data processing, please reopen this issue or launch a new one. Thank you! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Hi, @WUT-wuxigang, It is provided by the INTERACTION dataset.

**Comment by WUT-wuxigang** [comment]
Thank you for your reply, I found the problem, I downloaded the dataset version v1.2 and this file is not included in this version

从 Windows 版邮件发送

发件人: Xiaoyu006
发送时间: 2022年7月25日 17:18
收件人: Xiaoyu006/MATP-with-HEAT
抄送: WUT-wuxigang; Mention
主题: Re: [Xiaoyu006/MATP-with-HEAT] Interaction dataset process (Issue #4)

Thanks for your reply, I read your update carefully and I have generated a new question, how is validation-set-list_INTERACTION-dataset_v1.txt obtained during the track splitting process? Looking forward to your reply, thanks a lot! 从 Windows 版邮件发送 发件人: Xiaoyu006 发送时间: 2022年7月18日 14:30 主题: Re: [Xiaoyu006/MATP-with-HEAT] Interaction dataset process (Issue #4) Hi, @WUT-wuxigang and @Jctrp. Sorry for the inconvenience caused. I uploaded a file showing the data structure and instructions to obtain the sorted folder. Hope this update helps. I am going to close this issue. In case there are other problems with data processing, please reopen this issue or launch a new one. Thank you! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***>
Hi, @WUT-wuxigang, It is provided by the INTERACTION dataset.
